# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy React App on Surge

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Prepare for Yarn Installation
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build hello_react_yasirrais111.surge.sh --token ${{ secrets.SURGE_TOKEN }}
